name: CI

on:
  # Triggers the workflow only for the main branch with semantic-version-tag
  push:
    tags:
      - 'v*'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source
        uses: actions/checkout@v3

      - name: Build Gatsby assets
        run: docker-compose run build

      - name: Deploy to GitHub Pages public repo
        uses: JamesIves/github-pages-deploy-action@4.1.4
        with:
          branch: main  # Branch to deploy to in the GitHub Pages repository
          folder: public  # The folder the action should deploy
          repository-name: moovinzoo/moovinzoo.github.io  # The repository to deploy to
          ssh-key: ${{ secrets.PAT }}
          git-config-name: moovinzoo
          git-config-email: moovinzoo@gmail.com
